### ISSUE TITLE
Allow users to buy and sell BTC from the CLI

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#106]
- [x] A user would enter `B` or `S`, respectively, and be faced with a popup asking how much they'd like to buy or sell.

- [x] Sanitize input and exit if error.

- [x] Pass this to the backend.

-------

@shobrook Do your thing here

Since we have to write this functionality for the automated trading, and I already have the popup written, let's just get this in v1.

**Comment by alichtman** [comment]
We can put this in v2. I left some commented code for this in `bitvision-cli.js`

**Comment by shobrook** [comment]
Add function for generating a payload. Test in the backend using Bitstamp credentials.
