### ISSUE TITLE
Technical Indicator Data Changes

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#140]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/20600565/44297658-ce069000-a29a-11e8-82eb-d1c4609beaca.png">

- [x] Order Technical Indicators by length of the name, from shortest to longest
- [x] ~Add an extra space to the end of BUY to make it the same length as SELL.~

**Comment by alichtman** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/20600565/44307735-463d8600-a36d-11e8-9f1f-bac0324af454.png">
Should look like this when you're done

**Comment by shobrook** [comment]
Is there any way to left align all of this data? It really doesn't look good centered.
