### ISSUE TITLE
Price Data Changes

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#147]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/20600565/44514070-b78a7b00-a684-11e8-87ed-2808d6cb40ca.png">

- [x] Strip decimals past 2 or 3 places.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/20600565/44514257-3d0e2b00-a685-11e8-8602-8afae355701e.png">

- [x] Only give me an array with one set of price info.

**Comment by alichtman** [comment]
- [ ] Timestamp needs to include hour/min/sec.

**Comment by shobrook** [comment]
H/M/S is dropped since we're displaying daily price.

**Comment by alichtman** [comment]
Swap to MM/DD/YY format.
