### ISSUE TITLE
Run some checks

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#16]
Firstly, we should check Quandl for other candidate Blockchain-related datasets and, if we find any, test them out. Secondly, I'm not sure if the specificity and sensitivity calculations are correct in the analysis module––this needs to be checked. Lastly, let's check a random sample from each TA-Lib output to ensure the technical indicators are being calculated correctly. 

Oh and I'm using a TA-Lib wrapper that Mike built and it doesn't support all of our desired indicators. So that needs to be figured out eventually.

**Comment by alichtman** [comment]
Add these:

1. https://www.quandl.com/data/BCHAIN/TRVOU-Bitcoin-USD-Exchange-Trade-Volume
2. https://www.quandl.com/data/BCHAIN/MIOPM-Bitcoin-Mining-Operating-Margin
3. https://www.quandl.com/data/BCHAIN/TVTVR-Bitcoin-Trade-Volume-vs-Transaction-Volume-Ratio

**Comment by shobrook** [comment]
Two of those datasets don't contain any observations from after 2016, so they can't be included. I tested the other one and it didn't improve the model's performance, so let's leave that out too.

**Comment by shobrook** [comment]
Mike says he updated his TA-Lib wrapper but I haven't checked it yet.
