### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#17]

**Comment by alichtman** [comment]
And, after that, an even more fleshed-out README that we'll title a bit differently and publish...

**Comment by shobrook** [comment]
Fleshed-out meaning

**Comment by shobrook** [comment]
Formulas need to be fixed too.

**Comment by alichtman** [comment]
I think the fix is something to do with enabling `math_jax`

**Comment by shobrook** [comment]
> I just read that this feature is actually not supported by GitHub.
>
>For reference: github/pages-gem#307
>
>Potential solution is moving our README to a github.io page and configuring that to support math_jax. I'm not opposed to this. Thoughts, @shobrook?

**Comment by shobrook** [comment]
We could provide descriptions for each indicator instead of formulas. It's only important for the research paper, not people using our code.

**Comment by alichtman** [comment]
## NEEDED README CHANGES

1. Flesh out more
2. Descriptions for each indicator instead of formulas
