### ISSUE TITLE
Technical Indicator Parser Syntax Error

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#178]

**Comment by shobrook** [comment]
If the ticker.json file has less than < 20 entries, then technical indicators will be pulled from Quandl. Otherwise, we calculate indicators based on what's in ticker.json... this is what's failing (the issue is specifically with parsing the timestamps in ticker.json).

**Comment by shobrook** [comment]
Closed since we're not calculating technical indicators based on ticker data.
