### ISSUE TITLE
Read Portfolio Trading Data from config.json

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#179]
- [x] Autotrader enabled
- [x] Next trade time

**Comment by alichtman** [comment]
Blocked by @shobrook needing to fix cronjob first.

**Comment by shobrook** [comment]
Whether or not the autotrader is enabled should be determined on the front-end; when they toggle it, just set the `autrotrade_enabled` field in config.json to the opposite of its current value. 

I'll write the next trade timestamp into config.json in the backend whenever autotrading is toggled.

**Comment by shobrook** [comment]
Actually nvm, I change both values in the backend. You can just read these values from `config.json` in the frontend.
