### ISSUE TITLE
Research different time series analysis methods

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#18]
We should try decomposing each feature into trend, seasonal, and noise components. And not just because I read it in some random academic paper, I truly think de-noised versions of our features could improve the model's performance.

**Comment by shobrook** [comment]
Jk I barely know what I'm talking about.

**Comment by alichtman** [comment]
Brutal honesty. I like it.

**Comment by shobrook** [comment]
Is it better to live an incredible life based on lies or a terrible one based on truth? Either way, I still don't know what I'm talking about.

**Comment by shobrook** [comment]
I've been looking into wavelet transforms, a preprocessing technique for time series data. Here's an excerpt about it:

> Wavelet transform is applied for data denoising in this study since it has the ability to handle the non-stationary financial time series data. The key property of wavelet transform is that it can analyze the frequency components of financial time series with time simultaneously compared with the Fourier transform. Consequently, wavelet is useful in handling highly irregular financial time series.
> 
> This study applies the Haar function as the wavelet basis function because it can not only decompose the financial time series into time and frequency domain but also reduce the processing time significantly. The wavelet transform with the Haar function as a basis has a time complexity of O(n) with n denoting the size of the time series.

I'm pretty unfamiliar with this kind of math but this explanation of why it's useful seems to make sense. I think we should look for a Python implementation of the Haar function and see if we can apply it to our own feature set.

**Comment by shobrook** [comment]
So I did some research on Python implementations of wavelet transforms and found the PyWavelets package. Here's the code for applying a Haar transform to each of our features:

```python
def wavelet_transform(dataframe):
    transformed = dataset[["Date", "Trend"]].copy()

    for header in dataset.drop(["Date", "Trend"], axis=1).columns:
        time_series = dataset[header].tolist()
        cA, cD = pywt.dwt(time_series, "haar") # Outputs approximation and detail coefficients

        #cat = pywt.threshold(cA, np.std(cA)/2, mode="soft")
        #cdt = pywt.threshold(cD, np.std(cD)/2, mode="soft")

        #reconstructed = pywt.idwt(cat, cdt, "haar")
        transformed[header] = pd.Series(np.concatenate([cA, cD]))

    return transformed
```

Theoretically, this should work, but when I plot but when I plot the decomposed time series against the original, it doesn't look very... denoised. Here's the plot for BTC closing price:
![closing price decomposed](https://user-images.githubusercontent.com/18684735/36943277-3b1158d8-1f4c-11e8-82b6-da595468d7d2.png)

Honestly not sure what to do here. We should probably reach out to your Dad, @alichtman, because I don't know anything about this stuff.

**Comment by shobrook** [comment]
Fuck this.

**Comment by VijaiSurya** [comment]
Hey did you finally find out how to perform wavelet transform?

**Comment by alichtman** [comment]
> Fuck this.

That was a no, haha. Sorry mate
