### ISSUE TITLE
Check login credentials are correct

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#186]
Execute login command and return the result somehow

**Comment by shobrook** [comment]
Done. There is now a "logged_in" flag in the `config.json` file that will be set to True on a successful authentication, False on unsuccessful.

The Python command to call for authenticating is `python3 ../controller authenticate`

**Comment by alichtman** [comment]
Still have to implement frontend for this.

**Comment by alichtman** [comment]
Done
