### ISSUE TITLE
can not install marked-terminal dependency

### ISSUE THREAD

**Issue by giondo** [shobrook/BitVision#228]
root@6d5c6e54f432:/app-bitvision/BitVision# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

root@6d5c6e54f432:/app-bitvision/BitVision# npm i bitvision -g
/usr/local/bin/bitvision -> /usr/local/lib/node_modules/bitvision/index.js
/usr/local/lib
└── bitvision@1.1.4 

npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none was installed.

**Comment by alichtman** [comment]
Thanks for reporting this. This is a known bug, however, it should not impact your ability to run the software.

**Comment by alichtman** [comment]
This doesn't impact the usability of the software at all, and I'm not sure how to fix it (maybe an npm bug?), so I'm just going to close this. If you solve it, open a PR and we'd gladly accept it.
