### ISSUE TITLE
No information in UI is shown after installation and start, VERSION is not defined error

### ISSUE THREAD

**Issue by neoromantic** [shobrook/BitVision#230]
So, I've install all dependencies, and when I run BitVision, it starts, however, there is no information shown. Please refer to screenshot. Will be happy to provide additional details if needed.

When I exit application, I can see the error:

```
ReferenceError: VERSION is not defined
    at Object.callback (/usr/local/lib/node_modules/bitvision/index.js:303:36)
    at Screen.<anonymous> (/usr/local/lib/node_modules/bitvision/node_modules/blessed/lib/widgets/listbar.js:253:20)
    at Screen.EventEmitter._emit (/usr/local/lib/node_modules/bitvision/node_modules/blessed/lib/events.js:94:20)
    at Screen.EventEmitter.emit (/usr/local/lib/node_modules/bitvision/node_modules/blessed/lib/events.js:114:17)
    at Program.<anonymous> (/usr/local/lib/node_modules/bitvision/node_modules/blessed/lib/widgets/screen.js:593:12)
    at Program.emit (events.js:182:13)
    at /usr/local/lib/node_modules/bitvision/node_modules/blessed/lib/program.js:410:15
    at Array.forEach (<anonymous>)
    at ReadStream.input.on.input._keypressHandler (/usr/local/lib/node_modules/bitvision/node_modules/blessed/lib/program.js:408:23)
    at ReadStream.emit (events.js:182:13)
```

I've also downloaded json files from 'store' folder and put it directly in /usr/lib

Here's my versions:

```
➜  ~ python --version
Python 3.7.0
➜  ~ node -v
v10.4.1
➜  ~ uname -a
Darwin sergeys-mbp 18.2.0 Darwin Kernel Version 18.2.0: Fri Dec 14 18:43:36 PST 2018; root:xnu-4903.240.10~4/RELEASE_X86_64 x86_64
```

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/44672/51230040-37491700-1991-11e9-8a24-d3807335ecdb.png">

**Comment by alichtman** [comment]
Weird. I've never seen that error before. 

> I've also downloaded json files from 'store' folder and put it directly in /usr/lib

You should not have to do this. The data files will be generated if they do not exist.

We'll look into this some more when we have time.

**Comment by sh4d0v1** [comment]
I don't see any information after BitVision start either, but I also don't get that error thrown OP describes after exit. His screenshot is the same what I see after start though.

**Comment by neoromantic** [comment]
I don’t see error now too, so it’s not related. But still no data.

**Comment by shobrook** [comment]
Can you try updating the package? Some patches were just made that might fix this.

**Comment by sh4d0v1** [comment]
bitvision@1.1.5 still produces the error.

No data shown and "ReferenceError: VERSION is not defined" thrown on press of "h".

**Comment by sh4d0v1** [comment]
bitvision@1.1.6 doesn't crash anymore on press of "h", but shows a help popup, which can't get closed without exiting the whole program ("Q"/"q" doesn't do anything, "c" does work though).

There still is no data shown whatsoever, not after refreshing either.

**Comment by corsa** [comment]
Getting the same thing too, I had to copy all the .json files manually into the store folder, which enabled Bitvision to start, but getting the same VERSION error if hitting "h" for help, and getting no data in the UI.

**Comment by alichtman** [comment]
>  I had to copy all the .json files manually into the store folder, which enabled Bitvision to start

We generate the files if they don't exist, so I'm confused how this was a fix for that problem.

**Comment by corsa** [comment]
> > I had to copy all the .json files manually into the store folder, which enabled Bitvision to start
> 
> We generate the files if they don't exist, so I'm confused how this was a fix for that problem.

config.json was the only file that seemed to get generated in the store directory for me.

**Comment by alichtman** [comment]
Weird. Check this file out to see that the files will be created if they don't already exist: https://github.com/shobrook/BitVision/blob/master/services/retriever.py

**Comment by RED29** [comment]
I also don't have any connection and no data. The file retriever.py exist (/usr/local/lib/node_modules/bitvision/services/retriever.py).

I even deleted the file and replace it by the one from github.

**Comment by alichtman** [comment]
> I also don't have any connection and no data.

By no connection, do you mean internet connection? If you do, that would explain the issue. You definitely need an internet connection for this to work.

**Comment by RED29** [comment]
> > I also don't have any connection and no data.
> 
> By no connection, do you mean internet connection? If you do, that would explain the issue. You definitely need an internet connection for this to work.

No, excuse me that I didn't describe it in detail. 
What I mean that there is no fetching data. I can see that it stores the data in _store_ directory, but all the files are empty. Like this:

{
  "error": false,
  "data": []
}

**Comment by RED29** [comment]
> Huh. So it does return from the data fetching methods successfully, but it doesn't actually fetch any data...
> 
> Are all of the data files like that?

I can see that every file is the same, except:
- portfolio.json

{
  "error": true,
  "data": {
    "account_balance": "$0.00",
    "returns": "0.00%",
    "net_profit": "$0.00",
    "sharpe_ratio": "0.00",
    "buy_accuracy": "0.00%",
    "sell_accuracy": "0.00%",
    "total_trades": "0"
  }
}

and of-course the config file is not empty.

**Comment by alichtman** [comment]
> its not matching my account balance by the way

This is expected, as that feature hasn't been fully implemented yet.

**Comment by alichtman** [comment]
We've diagnosed what we think the problem could be and pushed a fix for it. Try it out to see if that works for you.

**Comment by alichtman** [comment]
@corsa confirmed this fixed the bug on his end. Closing this issue for now.
