### ISSUE TITLE
Can not update dash board UI

### ISSUE THREAD

**Issue by oragnejang** [shobrook/BitVision#237]
OS: Ubuntu 18.04

It cannot be updated the main screen.
I also tried to click refresh"R" button.
![image](https://user-images.githubusercontent.com/11746626/51296090-c58acf00-1a5d-11e9-8b93-854ca08e875e.png)

**Comment by alichtman** [comment]
Can you provide more information? Python version, node version, pip3 install lists, etc.

**Comment by RED29** [comment]
I think this is the same as #230

**Comment by alichtman** [comment]
Closing in favor of #230
