### ISSUE TITLE
Hangs on 'Fetching transaction history from Bitstamp...'

### ISSUE THREAD

**Issue by neoromantic** [shobrook/BitVision#239]
So, before I had an issue #230, after updating to the new version what happens is that application just completely hangs upon logging 'Fetching transaction history from Bitstamp...'

By completely hangs I mean that waiting for any reasonable time doesn't help, Ctrl+C, Ctrl+D don't do nothing, etc.

I also see this:

```
➜  store cat transactions.json 
{
  "error": true,
  "data": []
}% ```

**Comment by AMerkuri** [comment]
Same issue, just sits there and using 100% of cpu.
![image](https://user-images.githubusercontent.com/969989/51432176-07716c00-1c3c-11e9-8463-07ce8c843bff.png)

**Comment by shobrook** [comment]
Which version?

**Comment by AMerkuri** [comment]
1.1.7, tested on docker running Ubuntu 18.04 image

**Comment by neoromantic** [comment]
Same here on macOS and 1.1.7

**Comment by shobrook** [comment]
I haven't been able to reproduce this. If fetching transaction data fails, an error flag will be written to `transactions.json` like @neoromantic pointed out, but this won't stop BitVision from launching. 

This, and the fact that you can't send a SIGINT to the parent process, tells me that it's an issue with the child process that's spawned to execute the Python script that populates `transactions.json`. And @AMerkuri, it looks like you have multiple instances of BitVision running, but no Python processes running. Do you both have Python 3 installed? If so, what version, and how was it installed (Homebrew, Anaconda, etc.)?

**Comment by AMerkuri** [comment]
@shobrook 
![image](https://user-images.githubusercontent.com/969989/51660747-6aa22c00-1fb7-11e9-82cb-ceb9b0533fc4.png)

I am running under root with admin rights. I've tried killing BitVision and restarting multiple times.

**Comment by alichtman** [comment]
@AMerkuri Maybe try upgrading to Python 3.7? It's possible that Python 3.6 is incompatible with the scripts we wrote.

**Comment by AMerkuri** [comment]
@alichtman Works on Python 3.7

**Comment by alichtman** [comment]
@AMerkuri "Works" as in: "Upgrading to 3.7 solved the problem and this issue should be closed?"

Or should this be left unsolved?

**Comment by alichtman** [comment]
Ok. So, #235 is where we're triaging that. Updating the README to require Python 3.7 instead of Python 3+
