### ISSUE TITLE
Move the dashboard to a web based client

### ISSUE THREAD

**Issue by hgouveia** [shobrook/BitVision#244]
Would be very useful to move the dashboard to a Web Base client, just because the Terminal version crash quite often and is also heavy

since it use nodejs , this could be achieved very fast, not fancy UI is needed, just replicate the console ui, and keep the same functionality

**Comment by alichtman** [comment]
If you would like to build an alternative to the terminal viewer, that’s cool. We could add a selector to the start up screen that lets you pick between the terminal and a web app. I don’t believe @shobrook or I have any time to dedicate to this undertaking, but I’m willing to review the PR if/when someone builds it.
