### ISSUE TITLE
Explore other potential features

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#27]
Since most Bitcoin traders are probably 12 yrs old and clueless, it would be interesting to see if there's a correlation between price change and predictions made by popular Bitcoin forecasting websites. We should also look into Bitcoin Core's Github activity as a possible feature.

**Comment by shobrook** [comment]
Eh, let's just mention this in the "Future Work" section of the paper and leave it at that.

**Comment by alichtman** [comment]
> We should also look into Bitcoin Core's Github activity as a possible feature.

Maybe look at commit times? New feature = resparked interest?
