### ISSUE TITLE
Randomize the balanced train/test splitter

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#29]

**Comment by shobrook** [comment]
So this tells me essentially nothing: https://datascience.stackexchange.com/questions/28200/when-should-you-balance-a-time-series-dataset

Except that I should learn more about loss functions and try undersampling.

**Comment by alichtman** [comment]
Assuming the code in my latest merge works correctly, our work here is done.

**Comment by alichtman** [comment]
Although, tbh this issue should probably stay open until we test it fully.
