### ISSUE TITLE
Test an LSTM network

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#31]
Price prediction is fundamentally a sequence learning task, which LSTMs are designed for. LSTMs have what's called memory cells, which can store information that lies dozens of time-steps in the past. This is important because, in the market, cause and effect can be quite far apart.

I don't think Scikit-Learn supports LSTMs, so we'll have to use Keras. I'm reading [Understanding LSTMs](http://colah.github.io/posts/2015-08-Understanding-LSTMs/) and [Keras Guide to Sequential Learning](https://stackoverflow.com/questions/38714959/understanding-keras-lstms?rq=1) to learn about how LSTMs work and how to implement them.

**Comment by shobrook** [comment]
I expect this to significantly outperform the other models.

**Comment by shobrook** [comment]
The LSTM architecture described [here](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0180944) should be a useful reference.

**Comment by alichtman** [comment]
I just took a look at these and, well, good luck man.

**Comment by shobrook** [comment]
I actually have a solid, high-level understanding of how LSTMs and back-propagation work, but (and this is an issue specifically with Keras) I can't figure out how to reshape our feature set to actually train the LSTM, lol.

**Comment by alichtman** [comment]
We'll talk through it later.

**Comment by shobrook** [comment]
Okay this isn't happening
