### ISSUE TITLE
Turn this project into an automated trading algorithm

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#35]
This shouldn't be terribly complicated, but we need to diagram the user flow. On a high level, this is how it should work:

1) After installation, the user runs BitVision and enters their GDAX API key
2) All historical data is then re-scraped, preprocessed, and appended to the local file `training.csv`
3) Model is trained and serialized locally as `model.pkg`
4) Dashboard is populated with all relevant data and is refreshed every X seconds
5) Countdown begins for when the first trade is scheduled to execute
6) Once the countdown ends, input data is scraped and preprocessed, fed into the model which outputs a prediction, and then the trade is executed and stored in a local file `trading_log.csv`
7) Countdown resets, repeat 2) and 3)

And when the user exits BitVision, it needs to continue running in the background (until the laptop is shut off).

**Comment by alichtman** [comment]
> And when the user exits BitVision, it needs to continue running in the background.

Do we want this to be persistent across restarts? From a user protection standpoint, I wanna say no, but from a usability standpoint, maybe yes?

https://code.tutsplus.com/tutorials/managing-cron-jobs-using-python--cms-28231

**Comment by shobrook** [comment]
This issue is redundant.
