### ISSUE TITLE
Instead of using Bitstamp price data, use data averaged across multiple exchanges

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#39]
We want to avoid exchange-specific biases.

**Comment by shobrook** [comment]
It looks like Quandl deleted their 24hr average exchange rate dataset. We will probably have to pull each exchange's historical dataset and average them ourselves.

**Comment by themichaelusa** [comment]
Here's a suggestion. Take a weighted average of each exchange rate, where the weight is determined by the exchange's order book size (or total volume).

**Comment by alichtman** [comment]
@themichaelusa yeah that's what we were thinking

**Comment by alichtman** [comment]
Found average price data sets, but not average OHLCV data sets. We could calculate this ourselves by maybe averaging OHLCV data from a bunch of exchanges, but chances are we'll just go with the Bitstamp data.
