### ISSUE TITLE
Add the integral and rate-of-change of sentiment scores to the feature set

### ISSUE THREAD

**Issue by shobrook** [shobrook/BitVision#50]

**Comment by shobrook** [comment]
@alichtman Are these even the right transforms for this kinda data? Did you tell your Dad that sentiment was a nominal value?

**Comment by alichtman** [comment]
**Derivative Analysis** -- Change in sentiment from day to day. More days == more smoothing.

**Integral Analysis** -- Area under the curve. Shows accumulated sentiment. Higher number means more general positive sentiment over a period of time.

**Comment by shobrook** [comment]
Lmao, dude I know what derivatives and integrals are and what they'd show. I'm saying that sentiment is a categorical variable, not a continuous one, so the derivative will always be zero.

**Comment by alichtman** [comment]
We're looking at it over a period of time (we need to use some regression testing to pick the best length), so the derivative won't be zero, right?

**Comment by shobrook** [comment]
No. When you plot sentiment over time, it's going to be a series of horizontal lines.

**Comment by shobrook** [comment]
But I just realized this problem disappears if we use the weighted average sentiment values since they're continuous.

**Comment by shobrook** [comment]
So disregard :^)

**Comment by alichtman** [comment]
So, first step is going to be estimating a function for the average sentiment over each x day period, and then either:

1. Estimate definite integral from t -> t+x, where t+x is the most recent day in the analysis window
2. Take some average of the derivatives in the analysis window

For 1, [this SO post](https://stackoverflow.com/a/13323861/8740440) pretty much covers it.
Not 100% sure what to do about 2 yet.

**Comment by alichtman** [comment]
Just committed the integral analysis. Opening PR, but trying to get derivative done tonight too. 

Current thinking on 2. -> We have the data in the form of a list of average daily sentiment scores. I wrote a function to split them into a list of lists that would represent a sliding window. I could write a function to estimate a function for each list and then take the derivative at each day and average them from that. 

I haven't seen any libraries that have this capability yet, but I'm going to keep poking around for a little bit.

**Comment by shobrook** [comment]
I'll let you handle this tbh. Make sure both functions take in a dataframe that includes a column for sentiment.

**Comment by shobrook** [comment]
The xdata is time, the ydata is sentiment.

**Comment by shobrook** [comment]
Okay, so... fuck derivatives lets just do Rate of Change. :)

**Comment by shobrook** [comment]
Actually, since we're adding lag variables (i.e. we'll have sentiment at t, t-1, t-2, and t-3 in our feature set), is the derivative analysis really necessary? It's meant to show how sentiment is changing over time, but the lag variables already do that.

I'm gonna close this for now.
