### ISSUE TITLE
Develop caching method for data that is scraped

### ISSUE THREAD

**Issue by alichtman** [shobrook/BitVision#9]
I'm thinking that if the last time the code was run was less than ~10 minutes ago, the data set should **not** be updated, and should instead pull from a cached version. 

One possibility would be appending the current time to a txt file, and checking that against the last run-time before doing any data scraping. If they differ by whatever threshold we decide upon, just use the cached data.

**Comment by shobrook** [comment]
The threshold should be 24hrs as that’s how frequently Quandl updates their Bitcoin datasets.

Here’s a better option: On run, let’s save the fully preprocessed dataframe as a local CSV file. Then, on the next run, we can check the current time against the CSV’s last modification time and compare the difference against the threshold. If it’s less than the threshold, we’ll just use the CSV. This way we not only circumvent the data collection steps but also the preprocessing steps.

**Comment by alichtman** [comment]
Fixed this. Will be included in next pull request.
